// Code generated by schematic, DO NOT EDIT.
//
// Schema file: github.com/funvit/schematic/example/schema_with_defaults/schema/payload.go

package model

import (
	"fmt"
	"github.com/google/uuid"
	"strings"
	"time"
)

type Payload struct {
	int8   int8
	int16  int16
	int32  int32
	int64  int64
	uint8  uint8
	uint16 uint16
	uint32 uint32
	uint64 uint64
	bool   bool
	string string
	bytes  []byte
	uuid   uuid.UUID
	time   time.Time
}

func (m *Payload) String() string {

	var b strings.Builder

	b.WriteString("<Payload")
	b.WriteString(fmt.Sprintf(
		" int8:%v",
		m.int8,
	))
	b.WriteString(fmt.Sprintf(
		" int16:%v",
		m.int16,
	))
	b.WriteString(fmt.Sprintf(
		" int32:%v",
		m.int32,
	))
	b.WriteString(fmt.Sprintf(
		" int64:%v",
		m.int64,
	))
	b.WriteString(fmt.Sprintf(
		" uint8:%v",
		m.uint8,
	))
	b.WriteString(fmt.Sprintf(
		" uint16:%v",
		m.uint16,
	))
	b.WriteString(fmt.Sprintf(
		" uint32:%v",
		m.uint32,
	))
	b.WriteString(fmt.Sprintf(
		" uint64:%v",
		m.uint64,
	))
	b.WriteString(fmt.Sprintf(
		" bool:%v",
		m.bool,
	))
	b.WriteString(fmt.Sprintf(
		" string:%v",
		m.string,
	))

	b.WriteString(">")

	return b.String()
}

// GetInt8 gets field int8 value.
//
// Generated due to schema field marked with Getter().
//
// Note: getter can help to satisfy some interface(s).
func (m *Payload) GetInt8() int8 {
	return m.int8
}

// GetInt16 gets field int16 value.
//
// Generated due to schema field marked with Getter().
//
// Note: getter can help to satisfy some interface(s).
func (m *Payload) GetInt16() int16 {
	return m.int16
}

// GetInt32 gets field int32 value.
//
// Generated due to schema field marked with Getter().
//
// Note: getter can help to satisfy some interface(s).
func (m *Payload) GetInt32() int32 {
	return m.int32
}

// GetInt64 gets field int64 value.
//
// Generated due to schema field marked with Getter().
//
// Note: getter can help to satisfy some interface(s).
func (m *Payload) GetInt64() int64 {
	return m.int64
}

// GetUint8 gets field uint8 value.
//
// Generated due to schema field marked with Getter().
//
// Note: getter can help to satisfy some interface(s).
func (m *Payload) GetUint8() uint8 {
	return m.uint8
}

// GetUint16 gets field uint16 value.
//
// Generated due to schema field marked with Getter().
//
// Note: getter can help to satisfy some interface(s).
func (m *Payload) GetUint16() uint16 {
	return m.uint16
}

// GetUint32 gets field uint32 value.
//
// Generated due to schema field marked with Getter().
//
// Note: getter can help to satisfy some interface(s).
func (m *Payload) GetUint32() uint32 {
	return m.uint32
}

// GetUint64 gets field uint64 value.
//
// Generated due to schema field marked with Getter().
//
// Note: getter can help to satisfy some interface(s).
func (m *Payload) GetUint64() uint64 {
	return m.uint64
}

// GetBool gets field bool value.
//
// Generated due to schema field marked with Getter().
//
// Note: getter can help to satisfy some interface(s).
func (m *Payload) GetBool() bool {
	return m.bool
}

// GetString gets field string value.
//
// Generated due to schema field marked with Getter().
//
// Note: getter can help to satisfy some interface(s).
func (m *Payload) GetString() string {
	return m.string
}

// GetBytes gets field bytes value.
//
// Generated due to schema field marked with Getter().
//
// Note: getter can help to satisfy some interface(s).
func (m *Payload) GetBytes() []byte {
	return m.bytes
}

// GetUuid gets field uuid value.
//
// Generated due to schema field marked with Getter().
//
// Note: getter can help to satisfy some interface(s).
func (m *Payload) GetUuid() uuid.UUID {
	return m.uuid
}

// GetTime gets field time value.
//
// Generated due to schema field marked with Getter().
//
// Note: getter can help to satisfy some interface(s).
func (m *Payload) GetTime() time.Time {
	return m.time
}

// PayloadWithDefaults constructs model Payload
// with default values defined in schema.
//
// Example:
//
//    // construct a new model
//    myModel := PayloadWithDefaults()
//
//    // set public fields directly
//    myModel.SomePublicField = 4221
//
//    // or via setter (if generated)
//    myModel.SetName("Bob")
//
func PayloadWithDefaults() *Payload {
	return &Payload{
		int8:   8,
		int16:  16,
		int32:  32,
		int64:  64,
		uint8:  18,
		uint16: 116,
		uint32: 132,
		uint64: 164,
		bool:   true,
		string: "default string value",
		bytes:  []byte{115, 111, 109, 101, 32, 98, 121, 116, 101, 115},
		uuid:   uuid.MustParse("d540fd1b-8d05-4727-b3ff-56274ad606ee"),
		time:   time.Unix(100, 200),
	}
}
