// Code generated by schematic, DO NOT EDIT.
//
// Schema file: github.com/funvit/schematic/example/schema_with_defaults/schema/payload.go

package model

import (
	"errors"
	schemagen "github.com/funvit/schematic"
	"github.com/funvit/schematic/example/schema_with_defaults/schema"
	"github.com/funvit/schematic/field"
	"github.com/funvit/schematic/pkg/scope_error"
)

// region init

var (
	_ = errors.New("dummy")

	payloadModelFields       map[string]*field.Descriptor       // stores model fields
	payloadModelFieldsErrors map[string]*scope_error.ScopeError // stores model fields errors
)

func init() {
	// special code.

	m := schema.Payload{}

	payloadModelFields = make(map[string]*field.Descriptor, len(m.Fields()))
	for _, v := range m.Fields() {
		payloadModelFields[v.Descriptor().Name] = v.Descriptor()
	}

	payloadModelFieldsErrors = make(map[string]*scope_error.ScopeError, len(m.Fields()))
}

// endregion

// region model Payload validator

// Validate validates model by validators specified in schema.
//
// Returns nil if no validators are defined.
func (m *Payload) Validate() error {
	return schemagen.ValidateModel(m, payloadModelFields, payloadModelFieldsErrors)
}

// endregion
