// Code generated by schematic, DO NOT EDIT.
//
// Schema file: github.com/funvit/schematic/example/schema_with_validators/schema/account.go

package model

import (
	"fmt"
	"github.com/google/uuid"
	"strings"
	"time"
)

type Account struct {
	// Value auto-generated in repository.
	id    int64
	Login string
	Name  string
	// Value expected to be hashed.
	Password string
	// Used for soft-delete.
	IsDeleted        bool
	Rev              uuid.UUID
	SomeExternalUuid uuid.UUID
	Color            uint8
	MyByte           int8
	Binary           []byte
	CreatedAt        time.Time
}

func (m *Account) String() string {

	var b strings.Builder

	b.WriteString("<Account")
	b.WriteString(fmt.Sprintf(
		" id:%v",
		m.id,
	))
	b.WriteString(fmt.Sprintf(
		" Login:%v",
		m.Login,
	))
	b.WriteString(fmt.Sprintf(
		" Name:%v",
		m.Name,
	))
	b.WriteString(fmt.Sprintf(
		" Password:%v",
		"******", // sensitive

	))
	b.WriteString(fmt.Sprintf(
		" Rev:%v",
		m.Rev,
	))
	b.WriteString(fmt.Sprintf(
		" CreatedAt:%v",
		m.CreatedAt,
	))

	b.WriteString(">")

	return b.String()
}

// GetId gets field id value.
//
// Generated due to schema field marked with Getter().
//
// Note: getter can help to satisfy some interface(s).
func (m *Account) GetId() int64 {
	return m.id
}

// GetLogin gets field Login value.
//
// Generated due to schema field marked with Getter().
//
// Note: getter can help to satisfy some interface(s).
func (m *Account) GetLogin() string {
	return m.Login
}

// GetName gets field Name value.
//
// Generated due to schema field marked with Getter().
//
// Note: getter can help to satisfy some interface(s).
func (m *Account) GetName() string {
	return m.Name
}

// GetIsDeleted gets field IsDeleted value.
//
// Generated due to schema field marked with Getter().
//
// Note: getter can help to satisfy some interface(s).
func (m *Account) GetIsDeleted() bool {
	return m.IsDeleted
}

// SetLogin sets field Login value.
//
// Generated due to schema field marked with Setter().
//
// Note: setter can help to satisfy some interface(s).
func (m *Account) SetLogin(val string) {
	m.Login = val
}

// SetName sets field Name value.
//
// Generated due to schema field marked with Setter().
//
// Note: setter can help to satisfy some interface(s).
func (m *Account) SetName(val string) {
	m.Name = val
}

// SetIsDeleted sets field IsDeleted value.
//
// Generated due to schema field marked with Setter().
//
// Note: setter can help to satisfy some interface(s).
func (m *Account) SetIsDeleted(val bool) {
	m.IsDeleted = val
}

// AccountWithDefaults constructs model Account
// with default values defined in schema.
//
// Example:
//
//    // construct a new model
//    myModel := AccountWithDefaults()
//
//    // set public fields directly
//    myModel.SomePublicField = 4221
//
//    // or via setter (if generated)
//    myModel.SetName("Bob")
//
func AccountWithDefaults() *Account {
	return &Account{
		id: 0,
	}
}
