// Code generated by schematic, DO NOT EDIT.
//
// Schema file: github.com/funvit/schematic/example/schema_without_validators/schema/account.go

package model

import (
	"errors"
	schemagen "github.com/funvit/schematic"
	"github.com/funvit/schematic/example/schema_without_validators/schema"
	"github.com/funvit/schematic/field"
	"github.com/funvit/schematic/pkg/scope_error"
)

// region init

var (
	_ = errors.New("dummy")

	accountModelFields       map[string]*field.Descriptor       // stores model fields
	accountModelFieldsErrors map[string]*scope_error.ScopeError // stores model fields errors
)

func init() {
	// special code.

	m := schema.Account{}

	accountModelFields = make(map[string]*field.Descriptor, len(m.Fields()))
	for _, v := range m.Fields() {
		accountModelFields[v.Descriptor().Name] = v.Descriptor()
	}

	accountModelFieldsErrors = make(map[string]*scope_error.ScopeError, len(m.Fields()))
}

// endregion

// region model Account validator

// Validate validates model by validators specified in schema.
//
// Returns nil if no validators are defined.
func (m *Account) Validate() error {
	return schemagen.ValidateModel(m, accountModelFields, accountModelFieldsErrors)
}

// endregion
