// Code generated by schematic, DO NOT EDIT.
//
// Schema file: github.com/funvit/schematic/example/schema_without_validators/schema/account.go

package model

import (
	"github.com/google/uuid"
	"time"
)

type Account struct {
	// Value auto-generated in repository.
	Id    int64  `json:"id"`
	Login string `json:"login"`
	Name  string
	// Value expected to be hashed.
	Password string
	// Used for soft-delete.
	IsDeleted        bool
	Rev              uuid.UUID
	SomeExternalUuid uuid.UUID
	Color            uint8
	MyByte           int8
	Binary           []byte
	CreatedAt        time.Time
}

// AccountWithDefaults constructs model Account
// with default values defined in schema.
//
// Example:
//
//    // construct a new model
//    myModel := AccountWithDefaults()
//
//    // set public fields directly
//    myModel.SomePublicField = 4221
//
//    // or via setter (if generated)
//    myModel.SetName("Bob")
//
func AccountWithDefaults() *Account {
	return &Account{}
}
